@startuml
'https://plantuml.com/use-case-diagram

actor ac3 as "Pflanze"

ac1 -- uc1
ac1 -- uc2
ac1 -- uc3

ac2 -- uc4

@startuml

left to right direction

actor ac1 as "Hobby-Gärtner"
actor ac2 as "Bewässerungsanlage"
actor ac3 as "Feuchtigkeitssensor"
actor ac4 as "Gärtnermeister"

rectangle "PlantCare" {
usecase uc1 as "Allg. Pflanzeninformationen abfragen"
usecase uc2 as "Eigene Pflanzen verwalten"
usecase uc3 as "Bewässerungsanlage einrichten"
usecase uc4 as "Feuchtigkeitssensor einrichten"
usecase uc5 as "Bodenfeuchtigkeit auswerten"
usecase uc6 as "Pflanzendatenbank bewirtschaften"
usecase uc7 as "Pflanzen-Bewässerungalarm"
}


'Akteure rechte Seite
uc1 -- ac1
uc2 -- ac1
uc3 -- ac1
uc7 -- ac1
uc6 -- ac4

'Akteure linke Seite
ac2 "0..1"-- uc7
ac3 "0..*" -- uc5
ac3 "0..1" -- uc4
ac1 -- uc4
ac2 -- uc3

uc5 .> uc7: <<extends>>
uc5 .> uc2: <<extends>>
uc7 .> uc2: <<extends>>
uc1 .> uc2: <<extends>>
uc4 .> uc2: <<extends>>

@enduml

'https://forum.plantuml.net/8956/how-to-make-actors-appear-the-left-and-right-use-case-diagram